function validateSQL(sql) {

    if (
        !sql ||
        typeof sql !== "string"
    ) {

        throw new Error(
            "Invalid SQL generated by the model."
        );

    }


    const normalized =
        sql
            .trim()
            .toLowerCase();


    if (
        !normalized.startsWith("select") &&
        !normalized.startsWith("with")
    ) {

        throw new Error(
            "Only SELECT or WITH queries are allowed."
        );

    }


    /*
     * Remove one final semicolon.
     */
    const withoutTrailingSemicolon =
        normalized.replace(
            /;\s*$/,
            ""
        );


    /*
     * Prevent multiple SQL statements.
     */
    if (
        withoutTrailingSemicolon.includes(";")
    ) {

        throw new Error(
            "Multiple SQL statements are not allowed."
        );

    }


    const forbidden = [

        /\binsert\b/,

        /\bupdate\b/,

        /\bdelete\b/,

        /\bdrop\b/,

        /\balter\b/,

        /\btruncate\b/,

        /\bcreate\b/,

        /\bgrant\b/,

        /\brevoke\b/,

        /\bcopy\b/,

        /\bpg_sleep\b/,

        /\bcall\b/,

        /\bdo\b/

    ];


    for (
        const pattern
        of forbidden
    ) {

        if (
            pattern.test(normalized)
        ) {

            throw new Error(
                `Forbidden SQL detected: ${pattern}`
            );

        }

    }


    return true;

}


module.exports = {
    validateSQL
};